### ISSUE TITLE
N5110 Audio driver

### ISSUE THREAD

**Issue by nourserry** [Florin9doi/ACPI#1]
Hello Florin9doi,

I didn't really find a way to contact you, 
I found the updated N5110 UEFI bios on insanelymac, and I wanted to ask:
Did you find a fix for audio drivers issue on windows?

I'm dual booting and audio on Linux works perfectly, but I have the issue with Windows 10

I found your mention of the fix Dell sent for sandy bridge notebooks and I wonder if it is possible to implement somehow

**Comment by Florin9doi** [comment]
I haven't found any solution and it's unlikely anyone will invest more time for this 10 years old model.

**Comment by Florin9doi** [comment]
It had over the top support from community but it's time to move to something more modern, 768p is laughable for today.

**Comment by Florin9doi** [comment]
I haven't found any solution and it's unlikely anyone will invest more time for this 10 years old model.
It had over the top support from community but it's time to move to something more modern, 768p is laughable for today's standards.

**Comment by nourserry** [comment]
It's weird that linux (Manjaro to be specific) can handle it out of the box, I'm not sure if it's something in the grub config or something else.
If so, I think there may be something that gets it working.. 

On another topic, I'm interested to know how did you get UEFI working in the first place, I'd love to chat with you regarding that.

**Comment by Florin9doi** [comment]
>I'm interested to know how did you get UEFI working in the first place

This bios (like most of the computers released since 2012) is based on AMI Aptio, which is designed for UEFI boot, but for some reasons (:dollar:) Dell has decided that UEFI boot wont be supported by this low cost model. Luckily they didn't remove the support completely, only requiring to free some space and to reinsert the FatFS drivers. Being unsupported, Dell didn't bothered to test and fix the audio driver.

**Comment by nourserry** [comment]
If Dell fixed it in other sandy bridge devices, could it be just a simple extraction/insertion of the right parts with UEFITool?
or is hex editing required?

**Comment by Florin9doi** [comment]
They fixed a dozen of other issues at the same time (https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=g10jr&oscode=ww1&productcode=latitude-e6420) so to identify the change would require a lot of analysis. Moreover they use a different BIOS for Latitude - something in house instead of AMI Aptio - so the porting wouldn't be straight forward also.
Certainly is cheaper to buy a new laptop than to find and pay for someone with the necessary skills to finalize this task.
